on:
  pull_request:
    types: [opened, reopened]
    
jobs:
  gen_rules:
    runs-on: ubuntu-latest
    name: Automatically generate comby rules from the request
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 
          ref: ${{ github.event.pull_request.head.sha }}
          
        
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        
      - name: Generate comby rules
        uses: danieltrt/fixit@v0
        with:
          mountpoint: /github/workspace
          basesha: ${{ github.event.pull_request.base.sha }}
          
      - name: my-artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/generated_file.txt
      
