on:
  pull_request:
    types: [opened, reopened]
    
jobs:
  gen_rules:
    runs-on: ubuntu-latest
    name: Automatically generate comby rules from the request
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Hello world action step
        uses: danieltrt/fixit@v0
        with:
          mountpoint: /github/workspace
      - name: my-artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/generated_file.txt
      
